title: SciaticaSisters API
description: Documentation, tutorials, and reference pages for the Sciatica Sisters API
baseurl: "/SciaticaSisters-API"
url: "https://cae-west.github.io"
show_downloads: false
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme