title: ""
description: Build patient-first applications with the Sciatica Sisters API Documentation
baseurl: "/SciaticaSisters-API"
url: "https://cae-west.github.io"
show_downloads: false
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme